### ISSUE TITLE
Collaborate with NextGen to make Booter McGooter a feature of Mirth Connect or the NextGen Docker images

### ISSUE THREAD

**Issue by jonbartels** [jonbartels/bootermcgooter#2]
I implemented Booter McGooter because the upstream projects did not support this feature.

I do not have the time and energy to collaborate with the upstream maintainers to make this a first-class feature of Mirth Connect or the Docker images from NextGen.

Please collaborate with the https://github.com/nextgenhealthcare/connect or https://github.com/nextgenhealthcare/connect-docker projects to take the features from Booter McGooter and make them native features of Mirth Connect. Please reference this issue in any PRs you make to connect or connect-docker.

The goal is that if loading the server ID and env name is part of Connect, then Booter McGooter does not need to exist.

**Comment by rogin** [comment]
Opened [ticket](https://github.com/nextgenhealthcare/connect/issues/6208) and PR with connect.

**Comment by jonbartels** [comment]
Upstream PR from @rogin was merged https://github.com/nextgenhealthcare/connect/pull/6209#event-12976270099

This means it should be in the 4.6.0 release of Mirth. 

Once Mirth 4.6.0 is released Booter McGooter will no longer need to exist. Thank you for this work @rogin

**Comment by jonbartels** [comment]
Due to NG going closed source, the elimination of booter mcgooter is now in a different projectg https://github.com/OpenIntegrationEngine/engine/pull/46
